version: '3.8'

services:
  nextjs:
    build:
      context: ./server
      dockerfile: Dockerfile
    restart: always
    ports:
      - "42093:3000"
    volumes:
      - ./secrets/server-env:/app/.env

